// playlistGenerator.js
import { getAccessToken } from "./auth.js";

let moodMap = {};

export async function loadMoodMap() {
  const res = await fetch("data/moodMap.json");
  moodMap = await res.json();
}

export async function getGenresForMood(mood) {
  if (!moodMap[mood]) throw new Error(`No genres mapped for mood: ${mood}`);
  return moodMap[mood];
}

export async function searchTracks(genres, limit = 20) {
  const accessToken = getAccessToken();
  const seedGenre = genres[Math.floor(Math.random() * genres.length)];

  const res = await fetch(
    `https://api.spotify.com/v1/recommendations?seed_genres=${seedGenre}&limit=${limit}`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    }
  );

  const data = await res.json();
  return data.tracks;
}

export async function createPlaylist(tracks, mood) {
  const accessToken = getAccessToken();

  // Get current user ID
  const userRes = await fetch("https://api.spotify.com/v1/me", {
    headers: {
      Authorization: `Bearer ${accessToken}`
    }
  });

  const userData = await userRes.json();
  const userId = userData.id;

  // Create playlist
  const playlistRes = await fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      name: `Your ${mood} Mood Playlist`,
      description: `Generated by Music & Mood Matcher`,
      public: false
    })
  });

  const playlist = await playlistRes.json();

  // Add tracks
  const trackUris = tracks.map(track => track.uri);
  await fetch(`https://api.spotify.com/v1/playlists/${playlist.id}/tracks`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ uris: trackUris })
  });

  return playlist;
}